### ISSUE TITLE
Name wording is wrong, it isn't?

### ISSUE THREAD

**Issue by qgustavor** [qgustavor/what-is-this-anime#1]
I can rename the project ([again](https://github.com/qgustavor/what-is-this-anime/commit/fdeb5f1816af6a41f14cb09a8ede8088bf7c287c)), but it may create some problems.

**Comment by zcyzcy88** [comment]
**Don't rename.**
If it isn't broken, don't fix it.

**Comment by qgustavor** [comment]
@zcyzcy88 Whoa, there is someone beside me caring about this project! I will not rename it, but sorry for the bad English.
